<?php
$data = array (
  4 => 
  array (
    'cat_id' => '4',
    'cat_name' => '用药咨询',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '0',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 0,
    'id' => '4',
    'name' => '用药咨询',
  ),
  12 => 
  array (
    'cat_id' => '12',
    'cat_name' => '时尚美妆 专业药妆',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 0,
    'id' => '12',
    'name' => '时尚美妆 专业药妆',
  ),
  9 => 
  array (
    'cat_id' => '9',
    'cat_name' => '母婴专区 孕产健康',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 0,
    'id' => '9',
    'name' => '母婴专区 孕产健康',
  ),
  6 => 
  array (
    'cat_id' => '6',
    'cat_name' => '中西药品   心脑血管',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 0,
    'id' => '6',
    'name' => '中西药品   心脑血管',
  ),
  1 => 
  array (
    'cat_id' => '1',
    'cat_name' => '专科用药',
    'measure_unit' => '10000',
    'parent_id' => '0',
    'is_show' => '0',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 0,
    'id' => '1',
    'name' => '专科用药',
  ),
  13 => 
  array (
    'cat_id' => '13',
    'cat_name' => '医疗器械 血糖注射',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 0,
    'id' => '13',
    'name' => '医疗器械 血糖注射',
  ),
  10 => 
  array (
    'cat_id' => '10',
    'cat_name' => '成人用品 情趣用品',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 0,
    'id' => '10',
    'name' => '成人用品 情趣用品',
  ),
  7 => 
  array (
    'cat_id' => '7',
    'cat_name' => '男性专区 补肾壮阳',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 0,
    'id' => '7',
    'name' => '男性专区 补肾壮阳',
  ),
  2 => 
  array (
    'cat_id' => '2',
    'cat_name' => '医疗器械',
    'measure_unit' => '10000',
    'parent_id' => '0',
    'is_show' => '0',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 0,
    'id' => '2',
    'name' => '医疗器械',
  ),
  14 => 
  array (
    'cat_id' => '14',
    'cat_name' => '健康养生 增强免疫',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 0,
    'id' => '14',
    'name' => '健康养生 增强免疫',
  ),
  11 => 
  array (
    'cat_id' => '11',
    'cat_name' => '日常用药 感冒发烧',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 0,
    'id' => '11',
    'name' => '日常用药 感冒发烧',
  ),
  8 => 
  array (
    'cat_id' => '8',
    'cat_name' => '女性专区 孕妇用药',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 0,
    'id' => '8',
    'name' => '女性专区 孕妇用药',
  ),
);
?>